#DO THE TEST EACH 6 HOURS FROM MONDAY TO FRIDAY
name: OUR PIPELINE
on: 
 # schedule:
 # - cron: '0 */6 * * 5'
  
  push:
    branches:
     - 'main'
      
  workflow_dispatch:

jobs:
        
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
        - run: echo building
      
  deploy-dev:
    name: Unit Tests with Jest    
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      # Install required deps for action - jest, jest-html-report
      - name: Install Dependencies
        run: cd Unit_test_jest && npm install --save-dev jest jest-html-reporter 

      # Finally, run our tests
      - name: Run the tests
        run: cd Unit_test_jest && npm test
        
      - name: Generate report
        run:  cd Unit_test_jest && npm test
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: jest-report
          path: './test-report.html'
      - run: echo UPLOADING REPORT...
      
  testing-qa:
    name: Integration tests 1
    needs: [deploy-dev]
    runs-on: ubuntu-latest
    steps:
      - run: echo MOVED - QA
        
  deploy-stage:
    name: STAGE
    needs: [testing-qa]
    runs-on: ubuntu-latest
    steps:
      - run: echo HYPERCARE
      
  deploy-production:
    name: PRODUCTION
    needs: [deploy-stage]
    runs-on: ubuntu-latest
    steps:
      - run: echo GO-LIVE

  #test_schedule:
  build_int_test:
     name: Integration tests 2
     needs: [deploy-dev]
     runs-on: ubuntu-latest
     steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: run cypress tests with chrome
        uses: cypress-io/github-action@v3
        timeout-minutes: 10
        with:
          browser: chrome
      - name: Generate report
        run: cd cypress && npm run posttest
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: cypress-cucumber-report
          path: cypress/cucumber-report/
